/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallerautomotriz;

import java.util.ArrayList;

/**
 *
 * @author Jonathan Leony
 */
public class FormularioPrincipal extends javax.swing.JFrame {
    ArrayList vehiculos = new ArrayList();
    
    StockVehiculo stck = new StockVehiculo(vehiculos);
    
    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnlistado = new javax.swing.JButton();
        btntipo = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        btncomprar = new javax.swing.JButton();
        btnmostrarvehiculos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contenidoResultante = new javax.swing.JTextArea();
        campoVehiculo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        btntotal = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnrepuestos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Venta de Automoviles y Repuestos Leony´s S.A.");

        btnlistado.setText("Listado Honda Civic Disponible");
        btnlistado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistadoActionPerformed(evt);
            }
        });

        btntipo.setText("Tipo de Lineas Toyota");
        btntipo.setEnabled(false);
        btntipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntipoActionPerformed(evt);
            }
        });

        btnagregar.setText("Agregar Vehiculo");
        btnagregar.setEnabled(false);
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btncomprar.setText("Comprar Vehiculo");
        btncomprar.setEnabled(false);
        btncomprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomprarActionPerformed(evt);
            }
        });

        btnmostrarvehiculos.setText("Mostrar Vehiculos en Stock");
        btnmostrarvehiculos.setEnabled(false);
        btnmostrarvehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarvehiculosActionPerformed(evt);
            }
        });

        contenidoResultante.setColumns(20);
        contenidoResultante.setRows(5);
        jScrollPane1.setViewportView(contenidoResultante);

        jLabel2.setText("Ingrese Modelo de Vehiculo");

        jLabel3.setText("Ingrese Cantidad");

        jLabel4.setText("Ingrese Precio");

        btntotal.setText("Mostrar Total a Pagar");
        btntotal.setToolTipText("");
        btntotal.setEnabled(false);
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("PASO # 1 VISUALIZA NUESTRO LISTADO");

        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("PASO # 2 ESCOGE TU CARRO");

        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("PASO # 3 LO COMPRAS O NO?");

        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("PASO # 4 Y DE SER ASI, CUANTOS TE VAS A LLEVAR?");

        btnrepuestos.setText("Ir A Venta de Repuestos");
        btnrepuestos.setEnabled(false);
        btnrepuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrepuestosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnagregar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btncomprar)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btntotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnlistado)
                        .addGap(18, 18, 18)
                        .addComponent(btntipo))
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(btnmostrarvehiculos))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnrepuestos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnlistado)
                                            .addComponent(btntipo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(btnagregar))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btncomprar)
                                    .addComponent(campoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btntotal)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(btnrepuestos)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmostrarvehiculos)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlistadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistadoActionPerformed
       
        CivicTerceraGeneracion zapatillo = new CivicTerceraGeneracion();
        zapatillo.modelodisponible="De 1985 al 1988";
        zapatillo.color = "Disponibles en color Rojo y Negro";
        zapatillo.precio = 12000;    
        
        CivicQuintaGeneracion burbuja = new CivicQuintaGeneracion();
        burbuja.modelodisponible = "De 1990 al 1995";
        burbuja.color = "Disponibles en Azul y Amarillo";
        burbuja.precio = 18000;
        
        CivicSeptimaGeneracion moderno = new CivicSeptimaGeneracion();
        moderno.modelodisponible ="Del 2000 al 2006";
        moderno.color = "Disponibles en Negro y Gris";
        moderno.precio = 24000;
        
         contenidoResultante.setText("A continuación mostramos listado"+"\n"
                + "de Carros disponibles a la venta:" + "\n" + "\n" +
                 "HONDA CIVIC TERCERA GENERACION: " + "\n" +
                 zapatillo.modelodisponible +"\n" +
                 zapatillo.color + "\n" + "a un precio de: " +
                 zapatillo.precio + "\n" + "\n" +
                 "HONDA QUINTA GENERACION" + "\n" +
                 burbuja.modelodisponible + "\n" +
                 burbuja.color + "\n" + "a un precio de: " + 
                 burbuja.precio + "\n" + "\n" +
                 "HONDA SEPTIMA GENERACION" + "\n" +
                 moderno.modelodisponible + "\n" +
                 moderno.color + "\n" +
                 moderno.precio
                 
         );
         btnlistado.setEnabled(false);
         btntipo.setEnabled(true);
        
    }//GEN-LAST:event_btnlistadoActionPerformed

    private void btntipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntipoActionPerformed
       Toyota t1 = new Toyota ();
        contenidoResultante.setText(t1.familiar()+ "\n"
        + t1.deportivo() + "\n" +
                t1.todoterreno()
        );      
         btnlistado.setEnabled(false);
        btnagregar.setEnabled(true);
         btntipo.setEnabled(false);
        btnlistado.setEnabled(false);
    }//GEN-LAST:event_btntipoActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        stck.IngresarVehiculo(this.campoVehiculo.getText());
                contenidoResultante.setText("Agregúe Vehiculo en Stock");
        
         btnlistado.setEnabled(false);
        btntipo.setEnabled(false);
        btnmostrarvehiculos.setEnabled(true);
        
       
        
        
    
        
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnmostrarvehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarvehiculosActionPerformed
     
        
         contenidoResultante.setText("");
        contenidoResultante.append("LISTADO DE CARROS A LA VENTA:"+ "\n"+ "\n"+ stck.MostrarVehiculo(this.campoVehiculo.getText()));
        campoVehiculo.setText("");
        btncomprar.setEnabled(true);
        
    }//GEN-LAST:event_btnmostrarvehiculosActionPerformed

    private void btncomprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomprarActionPerformed
        
        stck.ComprarVehiculo(this.campoVehiculo.getText());
        contenidoResultante.setText("Tu compra fue realizada con éxito.");
         btnlistado.setEnabled(false);
        btntipo.setEnabled(false);
        btnmostrarvehiculos.setEnabled(true);
        btntotal.setEnabled(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btncomprarActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        Total t1 = new Total( Integer.parseInt(txtcantidad.getText()), Float.parseFloat(txtprecio.getText()));
        contenidoResultante.setText("El total a pagar es de: Q. "+ t1.resultado);
        btnrepuestos.setEnabled(true);
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btntotalActionPerformed

    private void btnrepuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrepuestosActionPerformed
        // TODO add your handling code here:
        new ingresorepuestos().show();
    }//GEN-LAST:event_btnrepuestosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btncomprar;
    private javax.swing.JButton btnlistado;
    private javax.swing.JButton btnmostrarvehiculos;
    private javax.swing.JButton btnrepuestos;
    private javax.swing.JButton btntipo;
    private javax.swing.JButton btntotal;
    private javax.swing.JTextField campoVehiculo;
    private javax.swing.JTextArea contenidoResultante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
